name: Run unit tests with Gradle

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests with Gradle
      run: ./gradlew test -Pdistribution=${{ secrets.DISTRIBUTION }}
