name: Run unit tests

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        
    - name: Build with Gradle
      run: ./gradlew build -Pdistribution=${{ secrets.DISTRIBUTION }}
      
    - name: Run unit tests
      run: ./gradlew test -Pdistribution=${{ secrets.DISTRIBUTION }}
