name: Gradle Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Gradle Test
      run: ./gradlew test
